export default [
    {
        title: "Cliffside Infinity Pool Retreat",
        description: "A quiet coastal hideaway with a private infinity pool overlooking the Amalfi shoreline.",
        image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=1200&q=80" },
        price: 28500,
        location: "Amalfi",
        country: "Italy",
        categories: ["Trending", "Amazing Pools", "Rooms"],
        geometry: { type: "Point", coordinates: [14.602, 40.628] },
        sampleReviews: [
            "The pool and sea views were spectacular, especially at sunset.",
            "A beautifully kept room and a peaceful place to unwind.",
            "The location made it easy to explore the coast. We would happily return.",
        ],
    },
    {
        title: "Glass Dome Under the Northern Lights",
        description: "Sleep beneath the Arctic sky in a heated glass dome just outside Rovaniemi.",
        image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1483347756197-71ef80e95f73?auto=format&fit=crop&w=1200&q=80" },
        price: 19800,
        location: "Rovaniemi",
        country: "Finland",
        categories: ["Trending", "Arctic", "Domes"],
        geometry: { type: "Point", coordinates: [25.7294, 66.5039] },
        sampleReviews: [
            "Watching the northern sky from bed was an unforgettable experience.",
            "Warm, comfortable, and wonderfully quiet despite the winter weather.",
            "The hosts gave us great tips for seeing the aurora nearby.",
        ],
    },
    {
        title: "A-Frame Camp by Lake Bled",
        description: "A compact timber cabin with a fire pit, forest trails, and the lake a short walk away.",
        image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?auto=format&fit=crop&w=1200&q=80" },
        price: 9400,
        location: "Bled",
        country: "Slovenia",
        categories: ["Trending", "Camping", "Mountains"],
        geometry: { type: "Point", coordinates: [14.108, 46.368] },
        sampleReviews: [
            "The cabin was cozy and the trail access was excellent.",
            "We loved having a fire outside after a day by the lake.",
            "A simple, comfortable base for exploring the Julian Alps.",
        ],
    },
    {
        title: "Canal Houseboat in Amsterdam",
        description: "A renovated houseboat with a sunny deck moored along a quiet canal near the old center.",
        image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80" },
        price: 16200,
        location: "Amsterdam",
        country: "Netherlands",
        categories: ["Trending", "Boats", "Iconic Cities"],
        geometry: { type: "Point", coordinates: [4.9041, 52.3676] },
        sampleReviews: [
            "Staying on the canal made the trip feel completely different.",
            "The deck was a lovely spot for breakfast before heading into town.",
            "Compact but thoughtfully arranged, with cafes close by.",
        ],
    },
    {
        title: "Lavender Farm Stay in Provence",
        description: "A restored stone guesthouse surrounded by lavender fields and working vineyards.",
        image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80" },
        price: 11700,
        location: "Aix-en-Provence",
        country: "France",
        categories: ["Trending", "Farms", "Rooms"],
        geometry: { type: "Point", coordinates: [5.4474, 43.5297] },
        sampleReviews: [
            "The fields around the property were beautiful in the morning light.",
            "A comfortable room, a generous breakfast, and a lovely garden.",
            "We enjoyed meeting the hosts and learning about the vineyard.",
        ],
    },
    {
        title: "Aurora Cabin Outside Tromso",
        description: "A warm cedar cabin with wide windows, designed for winter nights and aurora watching.",
        image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1200&q=80" },
        price: 17400,
        location: "Tromso",
        country: "Norway",
        categories: ["Trending", "Arctic", "Camping"],
        geometry: { type: "Point", coordinates: [18.9553, 69.6492] },
        sampleReviews: [
            "The cabin stayed warm and comfortable through a snowy weekend.",
            "We saw the aurora from the porch on our second night.",
            "A peaceful spot with easy access to Tromso and nearby trails.",
        ],
    },
    {
        title: "Desert Dome at Wadi Rum",
        description: "A private stargazing dome at a small desert camp, with guided walks among the sandstone cliffs.",
        image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?auto=format&fit=crop&w=1200&q=80" },
        price: 13600,
        location: "Wadi Rum",
        country: "Jordan",
        categories: ["Trending", "Domes", "Camping"],
        geometry: { type: "Point", coordinates: [35.4194, 29.5733] },
        sampleReviews: [
            "The stars were incredible and the dome was spotless.",
            "Our desert guide made the whole stay feel personal and memorable.",
            "A quiet night, a beautiful sunrise, and excellent local food.",
        ],
    },
    {
        title: "Highland Castle Estate",
        description: "A historic stone wing on a working Highland estate, surrounded by lochs and walking paths.",
        image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1585543805890-6051f7829f98?auto=format&fit=crop&w=1200&q=80" },
        price: 24200,
        location: "Inverness",
        country: "United Kingdom",
        categories: ["Trending", "Castles", "Mountains"],
        geometry: { type: "Point", coordinates: [-4.2247, 57.4778] },
        sampleReviews: [
            "The rooms had so much character and the grounds were beautiful.",
            "A memorable stay with lovely walks right from the estate.",
            "The host shared fascinating history and local recommendations.",
        ],
    },
    {
        title: "Lochside Castle Cottage",
        description: "A private cottage beside an old Highland castle, with a wood stove and views across the loch.",
        image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1200&q=80&sat=-20" },
        price: 15800,
        location: "Fort Augustus",
        country: "United Kingdom",
        categories: ["Trending", "Castles", "Rooms"],
        geometry: { type: "Point", coordinates: [-4.6827, 57.1449] },
        sampleReviews: [
            "The cottage was warm, quiet, and perfectly placed by the water.",
            "We loved the historic setting and the thoughtful details inside.",
            "A great base for a few relaxed days in the Highlands.",
        ],
    },
    {
        title: "Sailing Catamaran in the Cyclades",
        description: "A private cabin aboard a comfortable catamaran, with island-hopping trips from Paros harbor.",
        image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1540946485063-a40da27545f8?auto=format&fit=crop&w=1200&q=80" },
        price: 22100,
        location: "Paros",
        country: "Greece",
        categories: ["Trending", "Boats", "Amazing Pools"],
        geometry: { type: "Point", coordinates: [25.1489, 37.0853] },
        sampleReviews: [
            "Waking up on the water was the highlight of our island trip.",
            "The crew knew all the best coves and made us feel at home.",
            "Clean cabin, beautiful sailing days, and a very special experience.",
        ],
    },
    {
        title: "Tuscany Vineyard Farmhouse",
        description: "A farmhouse stay among olive groves and vineyards, with a cooking table overlooking the hills.",
        image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1518732714860-b62714ce0c59?auto=format&fit=crop&w=1200&q=80" },
        price: 14500,
        location: "Siena",
        country: "Italy",
        categories: ["Trending", "Farms", "Iconic Cities"],
        geometry: { type: "Point", coordinates: [11.3308, 43.3188] },
        sampleReviews: [
            "The countryside views and outdoor dinners were wonderful.",
            "We learned a lot about the farm and enjoyed every breakfast.",
            "Quiet, welcoming, and an easy drive to Siena.",
        ],
    },
    {
        title: "Palm Grove Pool Villa in Marrakech",
        description: "A private riad-style villa with a shaded courtyard pool, tucked among the palms outside the medina.",
        image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80" },
        price: 18900,
        location: "Marrakech",
        country: "Morocco",
        categories: ["Trending", "Amazing Pools", "Iconic Cities"],
        geometry: { type: "Point", coordinates: [-7.9811, 31.6295] },
        sampleReviews: [
            "The courtyard pool was a welcome break after exploring the medina.",
            "Beautiful architecture, attentive hosts, and a peaceful garden.",
            "The driver and restaurant recommendations made everything easy.",
        ],
    },
    {
        title: "Paris Seine Houseboat Studio",
        description: "A compact, renovated houseboat with a private deck and an easy walk to the riverfront markets.",
        image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?auto=format&fit=crop&w=1200&q=80" },
        price: 17800,
        location: "Paris",
        country: "France",
        categories: ["Boats", "Rooms", "Iconic Cities"],
        geometry: { type: "Point", coordinates: [2.3522, 48.8566] },
        sampleReviews: [
            "Falling asleep beside the Seine made our Paris trip special.",
            "Small but clever layout, and the deck was lovely in the morning.",
            "Easy access to the city with a peaceful place to return to.",
        ],
    },
    {
        title: "Venice Lagoon Sailing Cabin",
        description: "A private guest cabin aboard a classic sailing boat moored near the quieter edge of the lagoon.",
        image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80" },
        price: 19400,
        location: "Venice",
        country: "Italy",
        categories: ["Boats", "Rooms", "Iconic Cities"],
        geometry: { type: "Point", coordinates: [12.3155, 45.4408] },
        sampleReviews: [
            "A peaceful boat stay just outside the busiest canals.",
            "The host helped us plan a wonderful day on the lagoon.",
            "Clean cabin and a memorable way to experience Venice.",
        ],
    },
    {
        title: "Stockholm Archipelago Boat Stay",
        description: "A bright cabin on a small guest yacht, with island ferries and waterfront cafes nearby.",
        image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80" },
        price: 16800,
        location: "Stockholm",
        country: "Sweden",
        categories: ["Boats", "Rooms", "Iconic Cities"],
        geometry: { type: "Point", coordinates: [18.0686, 59.3293] },
        sampleReviews: [
            "The boat was comfortable and the harbor views were lovely.",
            "A unique stay with the city and the islands both close by.",
            "Everything was tidy, and the host made check-in simple.",
        ],
    },
    {
        title: "Copenhagen Canal Houseboat",
        description: "A light-filled houseboat with a small terrace in a walkable Copenhagen harbor neighborhood.",
        image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?auto=format&fit=crop&w=1200&q=80" },
        price: 18300,
        location: "Copenhagen",
        country: "Denmark",
        categories: ["Boats", "Rooms", "Iconic Cities"],
        geometry: { type: "Point", coordinates: [12.5683, 55.6761] },
        sampleReviews: [
            "We loved having coffee on the water before exploring the city.",
            "Comfortable cabin and a great neighborhood for walking.",
            "A calm, memorable stay with everything we needed onboard.",
        ],
    },
    {
        title: "Bavarian Castle Guest Wing",
        description: "A private guest wing in a restored castle near the foothills, with gardens and mountain paths close by.",
        image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1585543805890-6051f7829f98?auto=format&fit=crop&w=1200&q=80" },
        price: 23600,
        location: "Fussen",
        country: "Germany",
        categories: ["Castles", "Rooms", "Mountains"],
        geometry: { type: "Point", coordinates: [10.7019, 47.5696] },
        sampleReviews: [
            "The castle setting was beautiful and the room felt welcoming.",
            "We enjoyed the garden and the nearby mountain walks.",
            "A distinctive stay with thoughtful hosts and a great location.",
        ],
    },
    {
        title: "Loire Valley Castle Suite",
        description: "A quiet suite in a small Loire chateau, surrounded by vineyards and cycling routes.",
        image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1511818966892-d7d671e672a2?auto=format&fit=crop&w=1200&q=80" },
        price: 20700,
        location: "Tours",
        country: "France",
        categories: ["Castles", "Rooms"],
        geometry: { type: "Point", coordinates: [0.6848, 47.3941] },
        sampleReviews: [
            "The chateau was peaceful, elegant, and full of character.",
            "A lovely room and an ideal base for visiting nearby vineyards.",
            "Breakfast in the garden was a highlight of our stay.",
        ],
    },
    {
        title: "Edinburgh Castle View Rooms",
        description: "A restored townhouse guest suite with views toward the Old Town and Edinburgh Castle.",
        image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80" },
        price: 17200,
        location: "Edinburgh",
        country: "United Kingdom",
        categories: ["Castles", "Rooms", "Iconic Cities"],
        geometry: { type: "Point", coordinates: [-3.1883, 55.9533] },
        sampleReviews: [
            "The Old Town was right outside and the room was very comfortable.",
            "A great view and an easy walk to the castle and museums.",
            "The host's local tips made our Edinburgh weekend even better.",
        ],
    },
    {
        title: "Alpine Castle Lodge by Lake Bled",
        description: "A renovated guest lodge in a small lakeside castle, with alpine trails and the old town nearby.",
        image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1585543805890-6051f7829f98?auto=format&fit=crop&w=1200&q=80" },
        price: 18400,
        location: "Bled",
        country: "Slovenia",
        categories: ["Castles", "Rooms", "Mountains"],
        geometry: { type: "Point", coordinates: [14.108, 46.368] },
        sampleReviews: [
            "The castle setting and lake views made this a special stay.",
            "Comfortable rooms, friendly hosts, and excellent nearby walks.",
            "A great base for exploring Bled and the surrounding mountains.",
        ],
    },
    {
        title: "Icelandic Aurora Glass Dome",
        description: "A heated glass dome on a remote Icelandic ridge, with guided access to nearby hot springs.",
        image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=1200&q=80" },
        price: 21200,
        location: "Akureyri",
        country: "Iceland",
        categories: ["Arctic", "Domes", "Camping", "Mountains"],
        geometry: { type: "Point", coordinates: [-18.1262, 65.6885] },
        sampleReviews: [
            "We watched the sky change from the warmth of the dome.",
            "A comfortable glamping stay with incredible volcanic scenery.",
            "The hosts gave us clear directions and excellent hot spring tips.",
        ],
    },
    {
        title: "Lapland Forest Glass Igloo",
        description: "A private glass-roofed igloo among the Lapland pines, with a trailhead right outside.",
        image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1483347756197-71ef80e95f73?auto=format&fit=crop&w=1200&q=80" },
        price: 20400,
        location: "Saariselka",
        country: "Finland",
        categories: ["Arctic", "Domes", "Camping", "Mountains"],
        geometry: { type: "Point", coordinates: [27.4167, 68.4167] },
        sampleReviews: [
            "The forest was silent at night and the glass roof was perfect for stargazing.",
            "Warm beds, a tidy sauna, and a lovely walk just beyond the cabin.",
            "A comfortable outdoor escape with thoughtful winter details.",
        ],
    },
    {
        title: "Svalbard Fjord Dome Camp",
        description: "A small insulated dome camp with wide fjord views and guided excursions from Longyearbyen.",
        image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1518837695005-2083093ee35b?auto=format&fit=crop&w=1200&q=80" },
        price: 24800,
        location: "Longyearbyen",
        country: "Norway",
        categories: ["Arctic", "Domes", "Camping"],
        geometry: { type: "Point", coordinates: [15.6469, 78.2232] },
        sampleReviews: [
            "The fjord scenery was extraordinary and the dome stayed cozy.",
            "Our guide made the landscape feel accessible and safe to explore.",
            "A rare, peaceful place to stay with a wonderfully clear night sky.",
        ],
    },
    {
        title: "Yukon Mountain Aurora Dome",
        description: "A solar-powered dome on a Yukon mountain meadow, set up for winter camping and aurora viewing.",
        image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1200&q=80" },
        price: 19600,
        location: "Whitehorse",
        country: "Canada",
        categories: ["Arctic", "Domes", "Camping", "Mountains"],
        geometry: { type: "Point", coordinates: [-135.0568, 60.7212] },
        sampleReviews: [
            "The dome was warm, quiet, and perfectly placed for the night sky.",
            "A beautiful mountain setting and a surprisingly comfortable camp.",
            "We had a wonderful stay and appreciated the clear arrival instructions.",
        ],
    },
    {
        title: "Mallorca Olive Grove Farm Villa",
        description: "A restored finca among olive trees, with a private pool and long views across the countryside.",
        image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80" },
        price: 22600,
        location: "Pollenca",
        country: "Spain",
        categories: ["Farms", "Amazing Pools", "Rooms"],
        geometry: { type: "Point", coordinates: [3.0176, 39.8768] },
        sampleReviews: [
            "The pool and olive grove made it easy to spend a whole day at home.",
            "A spacious, spotless villa with a lovely outdoor dining area.",
            "The hosts shared great local food recommendations and beach routes.",
        ],
    },
    {
        title: "Douro Valley Vineyard Pool House",
        description: "A farmhouse suite on a family vineyard with a plunge pool overlooking the Douro hills.",
        image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1518732714860-b62714ce0c59?auto=format&fit=crop&w=1200&q=80" },
        price: 15900,
        location: "Peso da Regua",
        country: "Portugal",
        categories: ["Farms", "Amazing Pools", "Rooms"],
        geometry: { type: "Point", coordinates: [-7.7985, 41.1627] },
        sampleReviews: [
            "The vineyard views from the pool were incredible.",
            "We loved the relaxed farm setting and the local wine tasting.",
            "A comfortable suite and a very welcoming family-run stay.",
        ],
    },
    {
        title: "Normandy Orchard Farm Cottage",
        description: "A renovated orchard cottage with a heated pool, garden, and breakfast from the farm kitchen.",
        image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80" },
        price: 13200,
        location: "Bayeux",
        country: "France",
        categories: ["Farms", "Amazing Pools", "Rooms"],
        geometry: { type: "Point", coordinates: [-0.7031, 49.2765] },
        sampleReviews: [
            "The orchard was beautiful and the heated pool was a real treat.",
            "A cozy cottage with a thoughtful breakfast and peaceful garden.",
            "Perfect for slowing down between visits to the coast and Bayeux.",
        ],
    },
    {
        title: "Crete Citrus Farm Pool Stay",
        description: "A private stone guesthouse on a citrus farm, with a shaded pool and mountain views.",
        image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80" },
        price: 12800,
        location: "Chania",
        country: "Greece",
        categories: ["Farms", "Amazing Pools", "Rooms"],
        geometry: { type: "Point", coordinates: [24.018, 35.5138] },
        sampleReviews: [
            "The pool was peaceful and the citrus garden smelled wonderful.",
            "A clean, comfortable stay with excellent homemade breakfasts.",
            "We enjoyed the farm setting and the short drive to Chania.",
        ],
    },
];